### ISSUE TITLE
poketo-cli for mangarock of 3x3_eyes

### ISSUE THREAD

**Issue by taxaser** [poketo/poketo-cli#3] opened 2018-11-08 01:06 UTC
poketo https://mangarock.com/manga/mrs-serie-2263
just got 1-16chapter in few minutes... and no more...
System: windows 10.
![image](https://user-images.githubusercontent.com/1031857/48171153-8b9e9d80-e335-11e8-8573-954284199b0b.png)

**Comment by rosszurowski** [comment] 2018-11-08 04:21
Can you share the full error that was in the console?

**Comment by rosszurowski** [comment] 2018-11-08 04:31
Also, make sure that you're on the latest version. This command will upgrade the CLI:

```bash
npm i -g poketo-cli
```

**Comment by taxaser** [comment] 2018-11-08 06:17
no console ,only loading for >5hours twice.  for macOs && windows10 .

**Comment by taxaser** [comment] 2018-11-08 06:21
I suggest that downloading output specific loading information.

**Comment by rosszurowski** [comment] 2018-11-08 23:18
I just tried it myself on MacOS and I couldn't reproduce any hanging. Perhaps it was something with your internet connection?

The latest version of poketo-cli (0.0.3) has loading progress information, so if you upgrade you should be able to more accurately see if and where it's freezing:

![kapture 2018-11-09 at 8 15 19](https://user-images.githubusercontent.com/303731/48233252-dc76ca80-e3f7-11e8-8f54-a185284be57c.gif)

Can you try again with the version 0.0.3 (check with `poketo --version`) and let me know if it's still hanging?

**Comment by rosszurowski** [comment] 2018-11-08 23:55
Ahh, I just found what the issue might be. That series is published in volumes. I think, for example, "Volume 40 Chapter 6" was being saved to a "chapter-6" folder, which was then overwritten by "Volume 39 Chapter 6."

I just [pushed a fix](https://github.com/poketo/poketo-cli/commit/f3f27145833402d716fbeabdee318e9a63b9ca80) and published 0.0.4. If you upgrade and try again, it should be fixed.

**Comment by taxaser** [comment] 2018-11-09 07:42
thanks a lot!  it works!

**Closed as completed** 2018-11-10 11:23 UTC
